steps:
- uses: docker://docker:19.03.3
  secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
  runs: [sh, -uec]
  args:
  - |
    # cleanup name of image
    IMG=$(echo '$_STEP' | sed -e 's/\//-/g')

    docker build \
      -t getpopper/$IMG:$_VERSION \
      --build-arg VERSION=$_VERSION $_STEP

    # only push from master branch
    if [[ $GIT_BRANCH == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      docker push getpopper/$IMG:$_VERSION
    fi
