---
dist: xenial
language: python
python: 3.7
services: docker
env:
- STEP=geni VERSION=v0.9.9.2
- STEP=ansible VERSION=2.7.17
- STEP=ansible VERSION=2.8.11
- STEP=ansible VERSION=2.9.7
- STEP=ceph-ansible VERSION=v3.2.52
- STEP=ceph-ansible VERSION=v4.0.37
- STEP=ceph-ansible VERSION=v5.0.2
- STEP=csvtool VERSION=2.4
- STEP=hasura-cli VERSION=v1.2.2
- STEP=heroku-cli VERSION=7.42.1
- STEP=fio-plot VERSION=3.12-2
- STEP=r/rstudio VERSION=4.0.0
- STEP=r/verse VERSION=4.0.0
install:
- git clone https://github.com/getpopper/popper /tmp/popper
- pip install /tmp/popper/src
script:
- popper run --substitution _STEP=$STEP --substitution _VERSION=$VERSION -f .ci.yml
